name: inspect_pix
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    #state
  provider: ^4.0.5
  flutter_money_formatter: ^0.8.3
  search_widget: ^1.0.2
  buttons_tabbar: ^1.0.0+1

  cupertino_icons: ^0.1.3

  #google map
  google_maps_flutter: ^0.5.31

  multi_image_picker: ^4.7.12
  shape_of_view: ^1.0.2
  flutter_responsive_screen: ^1.0.0
  percent_indicator: ^2.1.6
  #page indicator
  smooth_page_indicator: ^0.1.5
  #animation
  simple_animations: ^1.3.3
  page_transition: ^1.1.6

  #toast
  toast: ^0.1.5

  #image picker
  flutter_native_image: ^0.0.5
  image_picker: ^0.6.7+4

  #font
  google_fonts: ^1.1.0
  #svg
  flutter_svg: ^0.18.1







dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/svg/
  fonts:
    - family: open sans regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: open sans semibold
      fonts:
        - asset: fonts/OpenSans-Semibold.ttf

    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
    - family: BottomNavIcons
      fonts:
        - asset: fonts/BottomNavIcons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
