/// Flutter icons BottomNavIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavIcons
///      fonts:
///       - asset: fonts/BottomNavIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomNavIcons {
  BottomNavIcons._();

  static const _kFontFam = 'BottomNavIcons';
  static const _kFontPkg = null;

  static const IconData m_dashboard = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_download = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
